#!/bin/bash
set -e
cd "$(dirname "$0")"
echo "Applying client list files..."
mkdir -p src/lib/clients
cat > src/lib/clients/data.ts.b64 <<'B64EOF'
aW1wb3J0IHsgc3VwYWJhc2UgfSBmcm9tICdAL2xpYi9zdXBhYmFzZSc7CgovKioKICogQ2xpZW50IGxpc3QgZGF0YSBsYXllciDigJQgcmVhZC1vbmx5LgogKgogKiBTY29wZSBpcyBkZWxpYmVyYXRlbHkgQ0EgKyBBQ1RJVkUgb25seToKICogIC0gYHNlcnZpY2VfdHlwZSA9ICdDQSdgIG1hdGNoZXMgQ0EgSG9tZSdzIGNvbnRyYWN0LiB0ZXN0cHJvMSBhbHNvIGhvbGRzIDEwCiAqICAgIEFDVElWRSAnUkEnIGNvbm5lY3Rpb25zOyB0aG9zZSBiZWxvbmcgdG8gYW4gUkEgc3VyZmFjZSwgbm90IHRoaXMgb25lLgogKiAgLSBgc3RhdHVzID0gJ0FDVElWRSdgIGlzIGxvYWQtYmVhcmluZyBmb3IgbmFtZXMuIFRoZSBgcHVibGljX3Byb2ZpbGVzYCB2aWV3CiAqICAgIG9ubHkgcmVzb2x2ZXMgYSBjbGllbnQncyBuYW1lIHdoZW4gYW4gQUNUSVZFIGNvbm5lY3Rpb24gZXhpc3RzLCBzbyBhCiAqICAgIG5vbi1BQ1RJVkUgZW50cnkgd291bGQgcmVuZGVyIGFzICJVbmtub3duIGNsaWVudCIgYnkgY29uc3RydWN0aW9uLgogKgogKiBUd28tc3RhZ2UgZmV0Y2gsIHNhbWUgc2hhcGUgYXMgdGhlIHZlcmlmaWVkIHdlYiBgQ2xpZW50c1ZpZXdgIHJlYWQgcGF0aDoKICogY29ubmVjdGlvbnMgZmlyc3QsIHRoZW4gbmFtZXMgZm9yIHRoZSByZXNvbHZlZCBpZCBsaXN0LgogKi8KZXhwb3J0IGludGVyZmFjZSBDbGllbnRMaXN0RW50cnkgewogIGNsaWVudElkOiBzdHJpbmc7CiAgbmFtZTogc3RyaW5nOwogIC8qKiBOdWxsIGZvciBzb21lIGNsaWVudHMgbGl2ZSAoMiBvZiA0NCBmb3IgdGVzdHBybzEpIOKAlCBuZXZlciBhc3N1bWUgcHJlc2VudC4gKi8KICBjaXR5OiBzdHJpbmcgfCBudWxsOwogIGNvbm5lY3RlZEF0OiBzdHJpbmcgfCBudWxsOwp9CgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gZmV0Y2hDbGllbnRMaXN0KHVzZXJJZDogc3RyaW5nKTogUHJvbWlzZTxDbGllbnRMaXN0RW50cnlbXT4gewogIGNvbnN0IHsgZGF0YTogY29ubnMsIGVycm9yOiBjb25uRXJyb3IgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAuZnJvbSgnY29ubmVjdGlvbnMnKQogICAgLnNlbGVjdCgnY2xpZW50X2lkLCBjb25uZWN0ZWRfYXQsIGNyZWF0ZWRfYXQnKQogICAgLmVxKCdwcm9mZXNzaW9uYWxfaWQnLCB1c2VySWQpCiAgICAuZXEoJ3NlcnZpY2VfdHlwZScsICdDQScpCiAgICAuZXEoJ3N0YXR1cycsICdBQ1RJVkUnKTsKCiAgaWYgKGNvbm5FcnJvcikgdGhyb3cgY29ubkVycm9yOwoKICBjb25zdCByb3dzID0gKGNvbm5zID8/IFtdKSBhcyB7IGNsaWVudF9pZDogc3RyaW5nIHwgbnVsbDsgY29ubmVjdGVkX2F0OiBzdHJpbmcgfCBudWxsOyBjcmVhdGVkX2F0OiBzdHJpbmcgfCBudWxsIH1bXTsKICBjb25zdCBpZHMgPSBBcnJheS5mcm9tKG5ldyBTZXQocm93cy5tYXAoKHIpID0+IHIuY2xpZW50X2lkKS5maWx0ZXIoKHYpOiB2IGlzIHN0cmluZyA9PiAhIXYpKSk7CiAgaWYgKGlkcy5sZW5ndGggPT09IDApIHJldHVybiBbXTsKCiAgY29uc3QgeyBkYXRhOiBwcm9maWxlcywgZXJyb3I6IHByb2ZFcnJvciB9ID0gYXdhaXQgc3VwYWJhc2UKICAgIC5mcm9tKCdwdWJsaWNfcHJvZmlsZXMnKQogICAgLnNlbGVjdCgndXNlcl9pZCwgbmFtZSwgY2l0eScpCiAgICAuaW4oJ3VzZXJfaWQnLCBpZHMpOwoKICBpZiAocHJvZkVycm9yKSB0aHJvdyBwcm9mRXJyb3I7CgogIGNvbnN0IGJ5SWQgPSBuZXcgTWFwPHN0cmluZywgeyBuYW1lOiBzdHJpbmcgfCBudWxsOyBjaXR5OiBzdHJpbmcgfCBudWxsIH0+KCk7CiAgZm9yIChjb25zdCBwIG9mIChwcm9maWxlcyA/PyBbXSkgYXMgeyB1c2VyX2lkOiBzdHJpbmc7IG5hbWU6IHN0cmluZyB8IG51bGw7IGNpdHk6IHN0cmluZyB8IG51bGwgfVtdKSB7CiAgICBieUlkLnNldChwLnVzZXJfaWQsIHsgbmFtZTogcC5uYW1lLCBjaXR5OiBwLmNpdHkgfSk7CiAgfQoKICBjb25zdCBlbnRyaWVzOiBDbGllbnRMaXN0RW50cnlbXSA9IHJvd3MKICAgIC5maWx0ZXIoKHIpOiByIGlzIHsgY2xpZW50X2lkOiBzdHJpbmc7IGNvbm5lY3RlZF9hdDogc3RyaW5nIHwgbnVsbDsgY3JlYXRlZF9hdDogc3RyaW5nIHwgbnVsbCB9ID0+ICEhci5jbGllbnRfaWQpCiAgICAubWFwKChyKSA9PiB7CiAgICAgIGNvbnN0IHAgPSBieUlkLmdldChyLmNsaWVudF9pZCk7CiAgICAgIHJldHVybiB7CiAgICAgICAgY2xpZW50SWQ6IHIuY2xpZW50X2lkLAogICAgICAgIG5hbWU6IHA/Lm5hbWUgPz8gJ1Vua25vd24gY2xpZW50JywKICAgICAgICBjaXR5OiBwPy5jaXR5ID8/IG51bGwsCiAgICAgICAgY29ubmVjdGVkQXQ6IHIuY29ubmVjdGVkX2F0ID8/IHIuY3JlYXRlZF9hdCA/PyBudWxsLAogICAgICB9OwogICAgfSk7CgogIGVudHJpZXMuc29ydCgoYSwgYikgPT4gYS5uYW1lLmxvY2FsZUNvbXBhcmUoYi5uYW1lKSk7CiAgcmV0dXJuIGVudHJpZXM7Cn0K
B64EOF
base64 -d < "src/lib/clients/data.ts.b64" > "src/lib/clients/data.ts"
rm "src/lib/clients/data.ts.b64"
mkdir -p src/features/clients
cat > src/features/clients/ClientRow.tsx.b64 <<'B64EOF'
aW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JzsKaW1wb3J0IHsgUHJlc3NhYmxlLCBTdHlsZVNoZWV0LCBWaWV3LCB1c2VDb2xvclNjaGVtZSB9IGZyb20gJ3JlYWN0LW5hdGl2ZSc7CgppbXBvcnQgeyBUaGVtZWRUZXh0IH0gZnJvbSAnQC9jb21wb25lbnRzL3RoZW1lZC10ZXh0JzsKaW1wb3J0IHsgQ29sb3JzLCBTcGFjaW5nIH0gZnJvbSAnQC9jb25zdGFudHMvdGhlbWUnOwppbXBvcnQgdHlwZSB7IENsaWVudExpc3RFbnRyeSB9IGZyb20gJ0AvbGliL2NsaWVudHMvZGF0YSc7CgovKioKICogT25lIGNsaWVudCByb3cuIE5vIGljb25zICh1bmF1ZGl0ZWQgZm9yIFJOKS4gVGhlIGVkZ2UgYmFyIHVzZXMKICogYGJhY2tncm91bmRTZWxlY3RlZGAgcmF0aGVyIHRoYW4gYW4gYWNjZW50IGtleSwgYmVjYXVzZSBvbmx5IHRoZSBwYWxldHRlCiAqIGtleXMgYWxyZWFkeSBwcm92ZW4gaW4gaW5kZXgudHN4L2FwcC10YWJzIHdlcmUgdXNlZCBoZXJlIOKAlCBubyBndWVzc2VkCiAqIGlkZW50aWZpZXJzLiBgY2l0eWAgaXMgb3B0aW9uYWwgaW4gbGl2ZSBkYXRhLCBzbyB0aGUgc3VidGl0bGUgaXMgY29uZGl0aW9uYWwuCiAqLwpleHBvcnQgZnVuY3Rpb24gQ2xpZW50Um93KHsgZW50cnksIG9uUHJlc3MgfTogeyBlbnRyeTogQ2xpZW50TGlzdEVudHJ5OyBvblByZXNzPzogKCkgPT4gdm9pZCB9KSB7CiAgY29uc3Qgc2NoZW1lOiAnbGlnaHQnIHwgJ2RhcmsnID0gdXNlQ29sb3JTY2hlbWUoKSA9PT0gJ2RhcmsnID8gJ2RhcmsnIDogJ2xpZ2h0JzsKICBjb25zdCBjID0gQ29sb3JzW3NjaGVtZV07CgogIHJldHVybiAoCiAgICA8UHJlc3NhYmxlCiAgICAgIG9uUHJlc3M9e29uUHJlc3N9CiAgICAgIGFjY2Vzc2liaWxpdHlSb2xlPSJidXR0b24iCiAgICAgIGFjY2Vzc2liaWxpdHlMYWJlbD17ZW50cnkubmFtZX0KICAgICAgc3R5bGU9eyh7IHByZXNzZWQgfSkgPT4gWwogICAgICAgIHN0eWxlcy5yb3csCiAgICAgICAgeyBiYWNrZ3JvdW5kQ29sb3I6IHByZXNzZWQgPyBjLmJhY2tncm91bmRTZWxlY3RlZCA6IGMuYmFja2dyb3VuZEVsZW1lbnQgfSwKICAgICAgXX0KICAgID4KICAgICAgPFZpZXcgc3R5bGU9e1tzdHlsZXMuZWRnZSwgeyBiYWNrZ3JvdW5kQ29sb3I6IGMuYmFja2dyb3VuZFNlbGVjdGVkIH1dfSAvPgogICAgICA8VmlldyBzdHlsZT17c3R5bGVzLmJvZHl9PgogICAgICAgIDxUaGVtZWRUZXh0IHR5cGU9InNtYWxsQm9sZCI+e2VudHJ5Lm5hbWV9PC9UaGVtZWRUZXh0PgogICAgICAgIHtlbnRyeS5jaXR5ID8gPFRoZW1lZFRleHQgdHlwZT0ic21hbGwiPntlbnRyeS5jaXR5fTwvVGhlbWVkVGV4dD4gOiBudWxsfQogICAgICA8L1ZpZXc+CiAgICA8L1ByZXNzYWJsZT4KICApOwp9Cgpjb25zdCBzdHlsZXMgPSBTdHlsZVNoZWV0LmNyZWF0ZSh7CiAgcm93OiB7CiAgICBmbGV4RGlyZWN0aW9uOiAncm93JywKICAgIGFsaWduSXRlbXM6ICdzdHJldGNoJywKICAgIGJvcmRlclJhZGl1czogU3BhY2luZy50d28sCiAgICBvdmVyZmxvdzogJ2hpZGRlbicsCiAgICBtaW5IZWlnaHQ6IDU2LAogIH0sCiAgZWRnZTogeyB3aWR0aDogNCB9LAogIGJvZHk6IHsKICAgIGZsZXg6IDEsCiAgICBwYWRkaW5nSG9yaXpvbnRhbDogU3BhY2luZy50aHJlZSwKICAgIHBhZGRpbmdWZXJ0aWNhbDogU3BhY2luZy50d28sCiAgICBqdXN0aWZ5Q29udGVudDogJ2NlbnRlcicsCiAgICBnYXA6IDIsCiAgfSwKfSk7Cg==
B64EOF
base64 -d < "src/features/clients/ClientRow.tsx.b64" > "src/features/clients/ClientRow.tsx"
rm "src/features/clients/ClientRow.tsx.b64"
mkdir -p src/app
cat > src/app/explore.tsx.b64 <<'B64EOF'
aW1wb3J0IFJlYWN0LCB7IHVzZUNhbGxiYWNrLCB1c2VFZmZlY3QsIHVzZVN0YXRlIH0gZnJvbSAncmVhY3QnOwppbXBvcnQgeyBQcmVzc2FibGUsIFJlZnJlc2hDb250cm9sLCBTY3JvbGxWaWV3LCBTdHlsZVNoZWV0LCBWaWV3LCB1c2VDb2xvclNjaGVtZSB9IGZyb20gJ3JlYWN0LW5hdGl2ZSc7CmltcG9ydCB7IFNhZmVBcmVhVmlldyB9IGZyb20gJ3JlYWN0LW5hdGl2ZS1zYWZlLWFyZWEtY29udGV4dCc7CgppbXBvcnQgeyBUaGVtZWRUZXh0IH0gZnJvbSAnQC9jb21wb25lbnRzL3RoZW1lZC10ZXh0JzsKaW1wb3J0IHsgVGhlbWVkVmlldyB9IGZyb20gJ0AvY29tcG9uZW50cy90aGVtZWQtdmlldyc7CmltcG9ydCB7IEJvdHRvbVRhYkluc2V0LCBDb2xvcnMsIE1heENvbnRlbnRXaWR0aCwgU3BhY2luZyB9IGZyb20gJ0AvY29uc3RhbnRzL3RoZW1lJzsKaW1wb3J0IHsgdXNlQXV0aCB9IGZyb20gJ0AvY29udGV4dC9hdXRoJzsKaW1wb3J0IHsgQ2xpZW50Um93IH0gZnJvbSAnQC9mZWF0dXJlcy9jbGllbnRzL0NsaWVudFJvdyc7CmltcG9ydCB7IGZldGNoQ2xpZW50TGlzdCwgdHlwZSBDbGllbnRMaXN0RW50cnkgfSBmcm9tICdAL2xpYi9jbGllbnRzL2RhdGEnOwoKLyoqCiAqIENsaWVudHMg4oCUIHJlYWQtb25seSAodjEgc2NvcGU6IGxpc3Qgb25seSwgbm8gYWRkL2VkaXQsIG5vIHdyaXRlcykuCiAqCiAqIFRoaXMgc2NyZWVuIHJlcGxhY2VzIHRoZSBzdG9jayBFeHBvICJFeHBsb3JlIiB0ZW1wbGF0ZSBzY3JlZW4uIFRoZSByb3V0ZQogKiBuYW1lIHN0YXlzIGBleHBsb3JlYCBkZWxpYmVyYXRlbHk6IHRoZSByb290IGxheW91dCByZW5kZXJzIE5hdGl2ZVRhYnMgd2l0aAogKiBleHBsaWNpdCB0cmlnZ2Vycywgc28gcmVuYW1pbmcgdGhlIGZpbGUgd291bGQgbWVhbiByZXN0cnVjdHVyaW5nIHRoZQogKiBuYXZpZ2F0b3IuIE9ubHkgdGhlIHRhYidzIHZpc2libGUgbGFiZWwgY2hhbmdlZC4KICoKICogQ2xpZW50IGRldGFpbCAocHJvZmlsZSArIElUUi9HU1QgZmlsaW5ncykgaXMgTk9UIGluIHRoaXMgc2NyZWVuIOKAlCByb3dzIGFyZQogKiBpbmVydCBwZW5kaW5nIGEgc3RhY2sgcm91dGUsIHdoaWNoIHRoZSBjdXJyZW50IE5hdGl2ZVRhYnMtb25seSBsYXlvdXQgaGFzCiAqIG5vIHBsYWNlIGZvciB5ZXQuCiAqLwpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBDbGllbnRzU2NyZWVuKCkgewogIGNvbnN0IHNjaGVtZTogJ2xpZ2h0JyB8ICdkYXJrJyA9IHVzZUNvbG9yU2NoZW1lKCkgPT09ICdkYXJrJyA/ICdkYXJrJyA6ICdsaWdodCc7CiAgY29uc3QgYyA9IENvbG9yc1tzY2hlbWVdOwogIGNvbnN0IHsgc2Vzc2lvbiB9ID0gdXNlQXV0aCgpOwogIGNvbnN0IHVzZXJJZCA9IHNlc3Npb24/LnVzZXI/LmlkID8/ICcnOwoKICBjb25zdCBbbG9hZGluZywgc2V0TG9hZGluZ10gPSB1c2VTdGF0ZSh0cnVlKTsKICBjb25zdCBbcmVmcmVzaGluZywgc2V0UmVmcmVzaGluZ10gPSB1c2VTdGF0ZShmYWxzZSk7CiAgY29uc3QgW2Vycm9yLCBzZXRFcnJvcl0gPSB1c2VTdGF0ZTxzdHJpbmcgfCBudWxsPihudWxsKTsKICBjb25zdCBbY2xpZW50cywgc2V0Q2xpZW50c10gPSB1c2VTdGF0ZTxDbGllbnRMaXN0RW50cnlbXT4oW10pOwoKICBjb25zdCBsb2FkID0gdXNlQ2FsbGJhY2soYXN5bmMgKCkgPT4gewogICAgaWYgKCF1c2VySWQpIHsKICAgICAgc2V0TG9hZGluZyhmYWxzZSk7CiAgICAgIHJldHVybjsKICAgIH0KICAgIHRyeSB7CiAgICAgIHNldEVycm9yKG51bGwpOwogICAgICBzZXRDbGllbnRzKGF3YWl0IGZldGNoQ2xpZW50TGlzdCh1c2VySWQpKTsKICAgIH0gY2F0Y2ggKGUpIHsKICAgICAgc2V0RXJyb3IoZSBpbnN0YW5jZW9mIEVycm9yID8gZS5tZXNzYWdlIDogJ0NvdWxkIG5vdCBsb2FkIHlvdXIgY2xpZW50cy4nKTsKICAgIH0gZmluYWxseSB7CiAgICAgIHNldExvYWRpbmcoZmFsc2UpOwogICAgICBzZXRSZWZyZXNoaW5nKGZhbHNlKTsKICAgIH0KICB9LCBbdXNlcklkXSk7CgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBsb2FkKCk7CiAgfSwgW2xvYWRdKTsKCiAgY29uc3Qgb25SZWZyZXNoID0gdXNlQ2FsbGJhY2soKCkgPT4gewogICAgc2V0UmVmcmVzaGluZyh0cnVlKTsKICAgIGxvYWQoKTsKICB9LCBbbG9hZF0pOwoKICByZXR1cm4gKAogICAgPFRoZW1lZFZpZXcgc3R5bGU9e3N0eWxlcy5jb250YWluZXJ9PgogICAgICA8U2FmZUFyZWFWaWV3IHN0eWxlPXtzdHlsZXMuc2FmZUFyZWF9PgogICAgICAgIDxTY3JvbGxWaWV3CiAgICAgICAgICBjb250ZW50Q29udGFpbmVyU3R5bGU9e3N0eWxlcy5jb250ZW50fQogICAgICAgICAgc2hvd3NWZXJ0aWNhbFNjcm9sbEluZGljYXRvcj17ZmFsc2V9CiAgICAgICAgICByZWZyZXNoQ29udHJvbD17PFJlZnJlc2hDb250cm9sIHJlZnJlc2hpbmc9e3JlZnJlc2hpbmd9IG9uUmVmcmVzaD17b25SZWZyZXNofSB0aW50Q29sb3I9e2MudGV4dH0gLz59CiAgICAgICAgPgogICAgICAgICAgPFZpZXcgc3R5bGU9e3N0eWxlcy5oZWFkZXJSb3d9PgogICAgICAgICAgICA8VGhlbWVkVGV4dCB0eXBlPSJ0aXRsZSI+Q2xpZW50czwvVGhlbWVkVGV4dD4KICAgICAgICAgICAgeyFsb2FkaW5nICYmICFlcnJvciA/ICgKICAgICAgICAgICAgICA8VGhlbWVkVGV4dCB0eXBlPSJzbWFsbCI+CiAgICAgICAgICAgICAgICB7Y2xpZW50cy5sZW5ndGh9IGFjdGl2ZQogICAgICAgICAgICAgIDwvVGhlbWVkVGV4dD4KICAgICAgICAgICAgKSA6IG51bGx9CiAgICAgICAgICA8L1ZpZXc+CgogICAgICAgICAge2xvYWRpbmcgPyAoCiAgICAgICAgICAgIDxUaGVtZWRUZXh0IHR5cGU9InNtYWxsIj5Mb2FkaW5nIHlvdXIgY2xpZW50c+KApjwvVGhlbWVkVGV4dD4KICAgICAgICAgICkgOiBlcnJvciA/ICgKICAgICAgICAgICAgPFZpZXcgc3R5bGU9e1tzdHlsZXMuZXJyb3JCb3gsIHsgYmFja2dyb3VuZENvbG9yOiBjLmRlc3RydWN0aXZlVGludCB9XX0+CiAgICAgICAgICAgICAgPFRoZW1lZFRleHQgdHlwZT0ic21hbGxCb2xkIiBzdHlsZT17eyBjb2xvcjogYy5kZXN0cnVjdGl2ZSB9fT4KICAgICAgICAgICAgICAgIHtlcnJvcn0KICAgICAgICAgICAgICA8L1RoZW1lZFRleHQ+CiAgICAgICAgICAgICAgPFByZXNzYWJsZSBvblByZXNzPXtvblJlZnJlc2h9PgogICAgICAgICAgICAgICAgPFRoZW1lZFRleHQgdHlwZT0ic21hbGxCb2xkIj5UYXAgdG8gcmV0cnk8L1RoZW1lZFRleHQ+CiAgICAgICAgICAgICAgPC9QcmVzc2FibGU+CiAgICAgICAgICAgIDwvVmlldz4KICAgICAgICAgICkgOiBjbGllbnRzLmxlbmd0aCA9PT0gMCA/ICgKICAgICAgICAgICAgPFZpZXcgc3R5bGU9e3N0eWxlcy5lbXB0eX0+CiAgICAgICAgICAgICAgPFRoZW1lZFRleHQgdHlwZT0ic21hbGxCb2xkIj5ObyBhY3RpdmUgY2xpZW50cyB5ZXQuPC9UaGVtZWRUZXh0PgogICAgICAgICAgICAgIDxUaGVtZWRUZXh0IHR5cGU9InNtYWxsIj4KICAgICAgICAgICAgICAgIENsaWVudHMgYXBwZWFyIGhlcmUgb25jZSBhIGNvbm5lY3Rpb24gcmVxdWVzdCBpcyBhY2NlcHRlZC4KICAgICAgICAgICAgICA8L1RoZW1lZFRleHQ+CiAgICAgICAgICAgIDwvVmlldz4KICAgICAgICAgICkgOiAoCiAgICAgICAgICAgIDxWaWV3IHN0eWxlPXtzdHlsZXMubGlzdH0+CiAgICAgICAgICAgICAge2NsaWVudHMubWFwKChlbnRyeSkgPT4gKAogICAgICAgICAgICAgICAgPENsaWVudFJvdyBrZXk9e2VudHJ5LmNsaWVudElkfSBlbnRyeT17ZW50cnl9IC8+CiAgICAgICAgICAgICAgKSl9CiAgICAgICAgICAgIDwvVmlldz4KICAgICAgICAgICl9CiAgICAgICAgPC9TY3JvbGxWaWV3PgogICAgICA8L1NhZmVBcmVhVmlldz4KICAgIDwvVGhlbWVkVmlldz4KICApOwp9Cgpjb25zdCBzdHlsZXMgPSBTdHlsZVNoZWV0LmNyZWF0ZSh7CiAgY29udGFpbmVyOiB7IGZsZXg6IDEsIGZsZXhEaXJlY3Rpb246ICdyb3cnLCBqdXN0aWZ5Q29udGVudDogJ2NlbnRlcicgfSwKICBzYWZlQXJlYTogeyBmbGV4OiAxLCBtYXhXaWR0aDogTWF4Q29udGVudFdpZHRoLCBhbGlnblNlbGY6ICdzdHJldGNoJyB9LAogIGNvbnRlbnQ6IHsKICAgIHBhZGRpbmdIb3Jpem9udGFsOiBTcGFjaW5nLnRocmVlLAogICAgcGFkZGluZ0JvdHRvbTogQm90dG9tVGFiSW5zZXQgKyBTcGFjaW5nLmZvdXIsCiAgICBnYXA6IFNwYWNpbmcuZm91ciwKICB9LAogIGhlYWRlclJvdzogewogICAgZmxleERpcmVjdGlvbjogJ3JvdycsCiAgICBhbGlnbkl0ZW1zOiAnY2VudGVyJywKICAgIGp1c3RpZnlDb250ZW50OiAnc3BhY2UtYmV0d2VlbicsCiAgICBwYWRkaW5nVG9wOiBTcGFjaW5nLnR3bywKICB9LAogIGxpc3Q6IHsgZ2FwOiBTcGFjaW5nLnR3byB9LAogIGVtcHR5OiB7IGdhcDogU3BhY2luZy5vbmUgfSwKICBlcnJvckJveDogeyBib3JkZXJSYWRpdXM6IFNwYWNpbmcudHdvLCBwYWRkaW5nOiBTcGFjaW5nLnRocmVlLCBnYXA6IFNwYWNpbmcudHdvIH0sCn0pOwo=
B64EOF
base64 -d < "src/app/explore.tsx.b64" > "src/app/explore.tsx"
rm "src/app/explore.tsx.b64"

python3 - <<'PYEDIT'
import io
p='src/components/app-tabs.tsx'
s=open(p).read()
assert '<NativeTabs.Trigger.Label>Explore</NativeTabs.Trigger.Label>' in s, 'app-tabs label not found'
s=s.replace('<NativeTabs.Trigger.Label>Explore</NativeTabs.Trigger.Label>','<NativeTabs.Trigger.Label>Clients</NativeTabs.Trigger.Label>')
open(p,'w').write(s)

p='src/app/index.tsx'
s=open(p).read()
old_imp="import { Pressable, RefreshControl, ScrollView, StyleSheet, View, useColorScheme } from 'react-native';"
new_imp="import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, View, useColorScheme } from 'react-native';"
assert old_imp in s, 'index.tsx react-native import not found'
s=s.replace(old_imp,new_imp,1)

anchor="  const onRefresh = useCallback(() => {"
assert anchor in s, 'index.tsx onRefresh anchor not found'
handler = """  // Triage rows carry only a destination slug, never a client id, so a press
  // cannot yet open a specific record. Surfacing that honestly beats an inert
  // tap. Adding `clientId` to TriageItem is the next slice.
  const handleNavigate = useCallback((href: string) => {
    const label =
      href === 'clients'
        ? 'Clients'
        : href === 'itr-generation'
          ? 'ITR filings'
          : href === 'gst-module'
            ? 'GST returns'
            : href === 'documents'
              ? 'Documents'
              : href === 'invoicing'
                ? 'Invoices'
                : href;
    Alert.alert(
      label,
      href === 'clients'
        ? 'Open the Clients tab to see your active clients.'
        : 'This screen is not built yet.',
    );
  }, []);

"""
s=s.replace(anchor, handler+anchor, 1)

old_nav='                onNavigate={() => {}}'
assert old_nav in s, 'index.tsx onNavigate not found'
s=s.replace(old_nav,'                onNavigate={handleNavigate}',1)
open(p,'w').write(s)
print('patched app-tabs.tsx and index.tsx')
PYEDIT

echo "Done."
